-module(gl_state_test).
-include_lib("eunit/include/eunit.hrl").

baseline_runtime_surface_test() ->
    gl_test_context:setup_context(),

    {ok, no_error} = gl:get_error(),
    {ok, Version} = gl:get_string(version),
    assert_nonempty_binary(Version),
    ok = indexed_string_check(),
    ok = state_limit_queries_check(),
    ok = state_detail_queries_check(),
    ok = state_limit_expansion_queries_check(),
    ok = pixel_store_state_queries_check(),
    ok = resource_limit_queries_check(),
    ok = fixed_resource_limit_queries_check(),
    ok = frontier_scalar_queries_check(),
    ok = int64_limit_queries_check(),
    ok = gl:cull_face(front),
    ok = gl:cull_face(back),
    ok = gl:cull_face(front_and_back),
    ok = gl:front_face(cw),
    ok = gl:front_face(ccw),
    ok = gl:line_width(1.0),
    ok = gl:scissor(0, 0, 1, 1),
    ok = gl:viewport(0, 0, 1, 1),
    ok = gl:hint(fragment_shader_derivative_hint, nicest),
    ok = gl:pixel_store(unpack_alignment, 1),
    ok = gl:pixel_store(pack_alignment, 1),
    ok = gl:color_mask(true, false, true, false),
    ok = gl:color_mask(true, true, true, true),
    ok = gl:clear_color(0.0, 0.0, 0.0, 1.0),
    ok = gl:clear([color_buffer_bit]),
    ok = read_pixels_check(),
    ok = gl:clear_stencil(0),
    ok = gl:depth_mask(true),
    ok = gl:depth_mask(false),
    ok = gl:stencil_mask(16#FF),
    ok = gl:stencil_func(always, 0, 16#FF),
    ok = gl:stencil_op(keep, keep, replace),
    ok = gl:stencil_func_separate(front, always, 0, 16#FF),
    ok = gl:stencil_op_separate(back, keep, keep, replace),
    ok = gl:stencil_mask_separate(front_and_back, 16#FF),
    ok = gl:blend_func(src_alpha, one_minus_src_alpha),
    ok = gl:blend_func_separate(src_alpha, one_minus_src_alpha, one, zero),
    ok = gl:blend_equation(func_add),
    ok = gl:blend_equation_separate(func_add, func_add),
    ok = gl:blend_color(0.25, 0.5, 0.75, 1.0),
    ok = gl:sample_coverage(0.5, false),
    ok = gl:sample_mask(0, 16#FFFFFFFF),
    ok = gl:memory_barrier([buffer_update_barrier_bit]),
    ok = gl:memory_barrier_by_region([framebuffer_barrier_bit]),
    ok = gl:flush(),
    ok = gl:finish(),
    ok = gl:clear_depth(1.0),
    ok = gl:depth_range(0.0, 1.0),
    ok = gl:depth_func(less),
    ok = gl:polygon_offset(1.0, 1.0),
    ok = gl:enable(scissor_test),
    {ok, true} = gl:is_enabled(scissor_test),
    ok = gl:disable(scissor_test),
    {ok, false} = gl:is_enabled(scissor_test),
    ok = gl:active_texture(texture0),
    {ok, [Texture]} = gl:gen_textures(1),
    ok = gl:bind_texture(texture_2d, Texture),
    ok = gl:tex_min_filter(texture_2d, nearest),
    ok = gl:tex_mag_filter(texture_2d, nearest),
    ok = gl:tex_wrap_s(texture_2d, clamp_to_edge),
    ok = gl:tex_wrap_t(texture_2d, clamp_to_edge),
    ok = gl:tex_parameter(f, texture_2d, texture_wrap_s, 33071.0),
    ok = gl:tex_parameter(f, texture_2d, texture_wrap_t, [33071.0]),
    ok = gl:tex_parameter(i, texture_2d, texture_wrap_s, [16#812F]),
    ok = gl:tex_storage_2d(texture_2d, 1, rgba8, 1, 1),
    ok = gl:bind_image_texture(0, Texture, 0, false, 0, read_write, rgba8),
    compute_dispatch_check(<<"#version 310 es\nlayout(local_size_x = 1) in;\nvoid main() {}\n">>),
    ok = gl:generate_mipmap(texture_2d),
    {ok, true} = gl:is_texture(Texture),
    ok = gl:bind_texture(texture_2d, none),
    ok = gl:delete_textures([Texture]),
    {ok, false} = gl:is_texture(Texture),
    {ok, [Texture3D]} = gl:gen_textures(1),
    ok = gl:bind_texture(texture_3d, Texture3D),
    ok = gl:tex_storage_3d(texture_3d, 1, rgba8, 1, 1, 1),
    {ok, true} = gl:is_texture(Texture3D),
    ok = gl:bind_texture(texture_3d, none),
    ok = gl:delete_textures([Texture3D]),
    {ok, false} = gl:is_texture(Texture3D),
    ok = texture_multisample_storage_check(),
    {ok, [Sampler]} = gl:gen_samplers(1),
    ok = sampler_binding_check(Sampler),
    ok = gl:delete_samplers([Sampler]),
    {ok, false} = gl:is_sampler(Sampler),
    {ok, [Pipeline]} = gl:gen_program_pipelines(1),
    ok = gl:bind_program_pipeline(Pipeline),
    {ok, true} = gl:is_program_pipeline(Pipeline),
    ok = gl:delete_program_pipelines([Pipeline]),
    {ok, [Buffer]} = gl:gen_buffers(1),
    ok = gl:bind_buffer(array_buffer, Buffer),
    {ok, true} = gl:is_buffer(Buffer),
    ok = gl:buffer_data(array_buffer, <<0, 1, 2, 3>>, static_draw),
    ok = gl:buffer_sub_data(array_buffer, 1, <<9, 8>>),
    ok = copy_buffer_sub_data_check(),
    ok = gl:bind_buffer_base(transform_feedback_buffer, 0, Buffer),
    ok = gl:bind_buffer_range(transform_feedback_buffer, 0, Buffer, 0, 4),
    {ok, [TransformFeedback]} = gl:gen_transform_feedbacks(1),
    ok = gl:bind_transform_feedback(transform_feedback, TransformFeedback),
    {ok, true} = gl:is_transform_feedback(TransformFeedback),
    ok = gl:delete_transform_feedbacks([TransformFeedback]),
    {ok, [Renderbuffer]} = gl:gen_renderbuffers(1),
    ok = gl:bind_renderbuffer(renderbuffer, Renderbuffer),
    {ok, true} = gl:is_renderbuffer(Renderbuffer),
    ok = gl:renderbuffer_storage(renderbuffer, rgba4, 1, 1),
    ok = gl:renderbuffer_storage_multisample(renderbuffer, 1, rgba4, 1, 1),
    {ok, [Framebuffer]} = gl:gen_framebuffers(1),
    ok = gl:bind_framebuffer(framebuffer, Framebuffer),
    {ok, true} = gl:is_framebuffer(Framebuffer),
    ok = gl:framebuffer_parameter(framebuffer, framebuffer_default_width, 1),
    ok = framebuffer_texture_attachment_check(),
    ok = gl:framebuffer_renderbuffer(framebuffer, color_attachment0, renderbuffer, Renderbuffer),
    {ok, framebuffer_complete} = gl:check_framebuffer_status(framebuffer),
    ok = gl:delete_framebuffers([Framebuffer]),
    {ok, false} = gl:is_framebuffer(Framebuffer),
    ok = gl:delete_renderbuffers([Renderbuffer]),
    {ok, false} = gl:is_renderbuffer(Renderbuffer),
    ok = blit_framebuffer_check(),
    ok = clear_buffer_value_check(),
    ok = clear_buffer_depth_stencil_check(),
    ok = copy_tex_image_check(),
    {ok, VertexShader} = gl:create_shader(vertex_shader),
    {ok, true} = gl:is_shader(VertexShader),
    ok = gl:shader_source(VertexShader, [[
        "attribute vec4 position; ",
        "uniform vec4 u_color; ",
        "varying vec4 v_color; ",
        "void main() { v_color = u_color; gl_Position = position; }"
    ]]),
    {ok, VertexShaderSource} = gl:get_shader_source(VertexShader, 4096),
    assert_nonempty_binary(VertexShaderSource),
    ok = gl:compile_shader(VertexShader),
    {ok, true} = gl:get_shader_compile_status(VertexShader),
    {ok, VertexShaderInfoLog} = gl:get_shader_info_log(VertexShader, 1024),
    assert_binary(VertexShaderInfoLog),
    ok = assert_shader_metadata(VertexShader),
    {ok, FragmentShader} = gl:create_shader(fragment_shader),
    {ok, true} = gl:is_shader(FragmentShader),
    ok = gl:shader_source(FragmentShader, [[
        "varying vec4 v_color; ",
        "void main() { gl_FragColor = v_color; }"
    ]]),
    {ok, FragmentShaderSource} = gl:get_shader_source(FragmentShader, 4096),
    assert_nonempty_binary(FragmentShaderSource),
    ok = gl:compile_shader(FragmentShader),
    {ok, true} = gl:get_shader_compile_status(FragmentShader),
    {ok, FragmentShaderInfoLog} = gl:get_shader_info_log(FragmentShader, 1024),
    assert_binary(FragmentShaderInfoLog),
    ok = assert_shader_metadata(FragmentShader),
    ok = gl:release_shader_compiler(),
    {ok, Program} = gl:create_program(),
    {ok, true} = gl:is_program(Program),
    ok = gl:attach_shader(Program, VertexShader),
    ok = gl:attach_shader(Program, FragmentShader),
    {ok, AttachedShaders} = gl:get_attached_shaders(Program, 2),
    ?assertEqual(lists:sort([VertexShader, FragmentShader]), lists:sort(AttachedShaders)),
    ok = gl:bind_attrib_location(Program, 0, ["pos", <<"ition">>]),
    ok = gl:program_parameter(Program, program_separable, 1),
    ok = gl:link_program(Program),
    {ok, ProgramInfoLog} = gl:get_program_info_log(Program, 1024),
    assert_binary(ProgramInfoLog),
    ok = assert_program_metadata(Program, 2),
    ok = assert_active_reflection_metadata(Program),
    {ok, 0} = gl:get_attrib_location(Program, ["pos", <<"ition">>]),
    {ok, ColorLocation} = gl:get_uniform_location(Program, ["u_", <<"color">>]),
    assert_non_negative_integer(ColorLocation),
    {ok, -1} = gl:get_uniform_location(Program, ["u_", <<"missing">>]),
    {ok, true} = gl:get_program_link_status(Program),
    ok = program_resource_lookup_check(Program),
    ok = gl:validate_program(Program),
    {ok, true} = gl:get_program_validation_status(Program),
    ok = uniform_block_check(es_uniform_block_vertex_source(), es_uniform_block_fragment_source()),
    ok = transform_feedback_varyings_check(
        es_transform_feedback_vertex_source(),
        es_transform_feedback_fragment_source()
    ),
    ok = fragment_data_location_query_check(),
    ok = program_pipeline_control_check(Program),
    {ok, [VertexArray]} = gl:gen_vertex_arrays(1),
    ok = gl:bind_vertex_array(VertexArray),
    {ok, true} = gl:is_vertex_array(VertexArray),
    ok = gl:vertex_attrib_pointer(0, 2, float, false, 0, 0),
    ok = gl:vertex_attrib_i_pointer(1, 2, int, 0, 0),
    ok = gl:vertex_attrib_divisor(0, 0),
    ok = gl:vertex_attrib(f, 0, 1.0),
    ok = gl:vertex_attrib(f, 0, {1.0, 0.0}),
    ok = gl:vertex_attrib(f, 0, {1.0, 0.0, 0.0}),
    ok = gl:vertex_attrib(f, 0, {1.0, 0.0, 0.0, 1.0}),
    ok = gl:bind_vertex_buffer(0, Buffer, 0, 4),
    ok = gl:vertex_attrib_binding(0, 0),
    ok = gl:vertex_attrib_format(0, 2, float, false, 0),
    ok = gl:vertex_attrib_i_format(1, 2, int, 0),
    ok = gl:vertex_binding_divisor(0, 0),
    ok = gl:vertex_attrib_i(i, 0, {1, 0, 0, 1}),
    ok = gl:vertex_attrib_i(ui, 0, {1, 0, 0, 1}),
    ok = gl:enable_vertex_attrib_array(0),
    ok = gl:disable_vertex_attrib_array(0),
    ok = gl:use_program(Program),
    ok = transform_feedback_operation_check(Buffer),
    ok = gl:uniform(f, -1, 1.0),
    ok = gl:uniform(i, -1, 1),
    ok = gl:uniform(f, -1, {1.0, 0.0}),
    ok = gl:uniform(f, -1, {1.0, 0.0, 0.0}),
    ok = gl:uniform(f, -1, {1.0, 0.0, 0.0, 1.0}),
    ok = gl:uniform(i, -1, {1, 0}),
    ok = gl:uniform(i, -1, {1, 0, 0}),
    ok = gl:uniform(i, -1, {1, 0, 0, 1}),
    ok = gl:uniform(ui, -1, 1),
    ok = gl:uniform(ui, -1, {1, 0}),
    ok = gl:uniform(ui, -1, {1, 0, 0}),
    ok = gl:uniform(ui, -1, {1, 0, 0, 1}),
    ok = gl:uniform(f, -1, [1.0]),
    ok = gl:uniform(f, -1, [{1.0, 0.0, 0.0, 1.0}]),
    ok = gl:uniform(i, -1, [1]),
    ok = gl:uniform(i, -1, [{1, 0, 0, 1}]),
    ok = gl:uniform(ui, -1, [1]),
    ok = gl:uniform(ui, -1, [{1, 0, 0, 1}]),
    ok = gl:uniform_matrix(f, -1, {{1.0, 0.0}, {0.0, 1.0}}),
    ok = gl:uniform_matrix(f, -1, [{{1.0, 0.0}, {0.0, 1.0}}]),
    ok = gl:uniform_matrix(f, -1,
        [{{1.0, 0.0, 0.0},
          {0.0, 1.0, 0.0}}]),
    ok = gl:uniform_matrix(f, -1,
        {{1.0, 0.0, 0.0},
         {0.0, 1.0, 0.0},
         {0.0, 0.0, 1.0}}),
    ok = gl:uniform_matrix(f, -1,
        {{1.0, 0.0, 0.0, 0.0},
         {0.0, 1.0, 0.0, 0.0},
         {0.0, 0.0, 1.0, 0.0},
         {0.0, 0.0, 0.0, 1.0}}),
    ok = gl:uniform_matrix(f, -1,
        {{1.0, 0.0, 0.0},
         {0.0, 1.0, 0.0}}),
    ok = gl:uniform_matrix(f, -1,
        {{1.0, 0.0},
         {0.0, 1.0},
         {0.0, 0.0}}),
    ok = gl:uniform_matrix(f, -1,
        {{1.0, 0.0, 0.0, 0.0},
         {0.0, 1.0, 0.0, 0.0}}),
    ok = gl:uniform_matrix(f, -1,
        {{1.0, 0.0},
         {0.0, 1.0},
         {0.0, 0.0},
         {0.0, 0.0}}),
    ok = gl:uniform_matrix(f, -1,
        {{1.0, 0.0, 0.0, 0.0},
         {0.0, 1.0, 0.0, 0.0},
         {0.0, 0.0, 1.0, 0.0}}),
    ok = gl:uniform_matrix(f, -1,
        {{1.0, 0.0, 0.0},
         {0.0, 1.0, 0.0},
         {0.0, 0.0, 1.0},
         {0.0, 0.0, 0.0}}),
    ok = gl:program_uniform(f, Program, -1, 1.0),
    ok = gl:program_uniform(f, Program, -1, {1.0, 0.0, 0.0, 1.0}),
    ok = gl:program_uniform(i, Program, -1, 1),
    ok = gl:program_uniform(i, Program, -1, {1, 0, 0, 1}),
    ok = gl:program_uniform(ui, Program, -1, 1),
    ok = gl:program_uniform(ui, Program, -1, {1, 0, 0, 1}),
    ok = gl:program_uniform(f, Program, -1, [1.0]),
    ok = gl:program_uniform(f, Program, -1, [{1.0, 0.0, 0.0, 1.0}]),
    ok = gl:program_uniform(i, Program, -1, [1]),
    ok = gl:program_uniform(i, Program, -1, [{1, 0, 0, 1}]),
    ok = gl:program_uniform(ui, Program, -1, [1]),
    ok = gl:program_uniform(ui, Program, -1, [{1, 0, 0, 1}]),
    ok = gl:program_uniform_matrix(f, Program, -1, {{1.0, 0.0}, {0.0, 1.0}}),
    ok = gl:program_uniform_matrix(f, Program, -1, [{{1.0, 0.0}, {0.0, 1.0}}]),
    ok = gl:program_uniform_matrix(f, Program, -1,
        [{{1.0, 0.0, 0.0},
          {0.0, 1.0, 0.0}}]),
    ok = gl:program_uniform_matrix(f, Program, -1,
        {{1.0, 0.0, 0.0},
         {0.0, 1.0, 0.0},
         {0.0, 0.0, 1.0}}),
    ok = gl:program_uniform_matrix(f, Program, -1,
        {{1.0, 0.0, 0.0, 0.0},
         {0.0, 1.0, 0.0, 0.0},
         {0.0, 0.0, 1.0, 0.0},
         {0.0, 0.0, 0.0, 1.0}}),
    ok = gl:program_uniform_matrix(f, Program, -1,
        {{1.0, 0.0, 0.0},
         {0.0, 1.0, 0.0}}),
    ok = gl:program_uniform_matrix(f, Program, -1,
        {{1.0, 0.0},
         {0.0, 1.0},
         {0.0, 0.0}}),
    ok = gl:program_uniform_matrix(f, Program, -1,
        {{1.0, 0.0, 0.0, 0.0},
         {0.0, 1.0, 0.0, 0.0}}),
    ok = gl:program_uniform_matrix(f, Program, -1,
        {{1.0, 0.0},
         {0.0, 1.0},
         {0.0, 0.0},
         {0.0, 0.0}}),
    ok = gl:program_uniform_matrix(f, Program, -1,
        {{1.0, 0.0, 0.0, 0.0},
         {0.0, 1.0, 0.0, 0.0},
         {0.0, 0.0, 1.0, 0.0}}),
    ok = gl:program_uniform_matrix(f, Program, -1,
        {{1.0, 0.0, 0.0},
         {0.0, 1.0, 0.0},
         {0.0, 0.0, 1.0},
         {0.0, 0.0, 0.0}}),
    {ok, [Query]} = gl:gen_queries(1),
    ok = gl:begin_query(any_samples_passed, Query),
    ok = gl:draw_arrays(triangles, 0, 0),
    ok = gl:draw_arrays_instanced(triangles, 0, 0, 1),
    ok = gl:end_query(any_samples_passed),
    {ok, true} = gl:is_query(Query),
    ok = gl:delete_queries([Query]),
    {ok, false} = gl:is_query(Query),
    ok = gl:use_program(none),
    ok = gl:bind_vertex_array(none),
    ok = gl:delete_vertex_arrays([VertexArray]),
    {ok, false} = gl:is_vertex_array(VertexArray),
    ok = gl:bind_buffer(array_buffer, none),
    ok = gl:delete_buffers([Buffer]),
    {ok, false} = gl:is_buffer(Buffer),
    ok = gl:detach_shader(Program, FragmentShader),
    ok = gl:detach_shader(Program, VertexShader),
    ok = gl:delete_shader(FragmentShader),
    ok = gl:delete_shader(VertexShader),
    {ok, false} = gl:is_shader(FragmentShader),
    {ok, false} = gl:is_shader(VertexShader),
    ok = gl:delete_program(Program),
    {ok, false} = gl:is_program(Program),
    {ok, no_error} = gl:get_error().

program_resource_lookup_check(Program) ->
    {ok, 16#FFFFFFFF} = gl:get_program_resource_index(Program, uniform, ["u_", <<"missing">>]),
    {ok, -1} = gl:get_program_resource_location(Program, uniform, ["u_", <<"missing">>]),
    ok.

transform_feedback_operation_check(Buffer) ->
    {ok, [Feedback]} = gl:gen_transform_feedbacks(1),
    ok = gl:bind_transform_feedback(transform_feedback, Feedback),
    ok = gl:bind_buffer_base(transform_feedback_buffer, 0, Buffer),
    ok = gl:begin_transform_feedback(points),
    {ok, invalid_operation} = gl:get_error(),
    ok = gl:pause_transform_feedback(),
    {ok, invalid_operation} = gl:get_error(),
    ok = gl:resume_transform_feedback(),
    {ok, invalid_operation} = gl:get_error(),
    ok = gl:end_transform_feedback(),
    {ok, invalid_operation} = gl:get_error(),
    ok = gl:delete_transform_feedbacks([Feedback]).

framebuffer_texture_attachment_check() ->
    {ok, [Texture2D]} = gl:gen_textures(1),
    ok = gl:bind_texture(texture_2d, Texture2D),
    ok = gl:framebuffer_texture_2d(framebuffer, color_attachment0, texture_2d, Texture2D, 0),
    {ok, [Texture3D]} = gl:gen_textures(1),
    ok = gl:bind_texture(texture_3d, Texture3D),
    ok = gl:framebuffer_texture_layer(framebuffer, color_attachment0, Texture3D, 0, 0),
    ok = gl:bind_texture(texture_2d, none),
    ok = gl:bind_texture(texture_3d, none),
    ok = gl:delete_textures([Texture2D, Texture3D]).

texture_multisample_storage_check() ->
    {ok, [Texture2D]} = gl:gen_textures(1),
    ok = gl:bind_texture(texture_2d_multisample, Texture2D),
    ok = gl:tex_storage_2d_multisample(texture_2d_multisample, 1, rgba8, 1, 1, true),
    ok = gl:bind_texture(texture_2d_multisample, none),
    ok = gl:delete_textures([Texture2D]).

copy_buffer_sub_data_check() ->
    {ok, [ReadBuffer]} = gl:gen_buffers(1),
    {ok, [WriteBuffer]} = gl:gen_buffers(1),
    ok = gl:bind_buffer(copy_read_buffer, ReadBuffer),
    ok = gl:buffer_data(copy_read_buffer, <<0, 1, 2, 3>>, static_draw),
    ok = gl:bind_buffer(copy_write_buffer, WriteBuffer),
    ok = gl:buffer_data(copy_write_buffer, 4, static_draw),
    ok = gl:copy_buffer_sub_data(copy_read_buffer, copy_write_buffer, 0, 0, 4),
    ok = gl:delete_buffers([ReadBuffer, WriteBuffer]).

blit_framebuffer_check() ->
    {ok, [ReadFramebuffer]} = gl:gen_framebuffers(1),
    {ok, [DrawFramebuffer]} = gl:gen_framebuffers(1),
    {ok, [ReadRenderbuffer]} = gl:gen_renderbuffers(1),
    {ok, [DrawRenderbuffer]} = gl:gen_renderbuffers(1),
    ok = gl:bind_renderbuffer(renderbuffer, ReadRenderbuffer),
    ok = gl:renderbuffer_storage(renderbuffer, rgba4, 1, 1),
    ok = gl:bind_framebuffer(read_framebuffer, ReadFramebuffer),
    ok = gl:framebuffer_renderbuffer(read_framebuffer, color_attachment0, renderbuffer, ReadRenderbuffer),
    ok = gl:read_buffer(color_attachment0),
    {ok, framebuffer_complete} = gl:check_framebuffer_status(read_framebuffer),
    ok = gl:bind_renderbuffer(renderbuffer, DrawRenderbuffer),
    ok = gl:renderbuffer_storage(renderbuffer, rgba4, 1, 1),
    ok = gl:bind_framebuffer(draw_framebuffer, DrawFramebuffer),
    ok = gl:framebuffer_renderbuffer(draw_framebuffer, color_attachment0, renderbuffer, DrawRenderbuffer),
    ok = gl:draw_buffers([color_attachment0]),
    {ok, framebuffer_complete} = gl:check_framebuffer_status(draw_framebuffer),
    ok = gl:blit_framebuffer(0, 0, 1, 1, 0, 0, 1, 1, [color_buffer_bit], nearest),
    ok = gl:invalidate_framebuffer(draw_framebuffer, [color_attachment0]),
    ok = gl:invalidate_sub_framebuffer(draw_framebuffer, [color_attachment0], 0, 0, 1, 1),
    ok = gl:delete_framebuffers([ReadFramebuffer, DrawFramebuffer]),
    ok = gl:delete_renderbuffers([ReadRenderbuffer, DrawRenderbuffer]).

clear_buffer_value_check() ->
    ok = clear_buffer_value_check(rgba4, f, [0.0, 0.0, 0.0, 1.0]),
    ok = clear_buffer_value_check(rgba8i, i, [0, 0, 0, 0]),
    ok = clear_buffer_value_check(rgba8ui, ui, [0, 0, 0, 0]).

clear_buffer_value_check(InternalFormat, Type, Value) ->
    {ok, [Framebuffer]} = gl:gen_framebuffers(1),
    {ok, [Renderbuffer]} = gl:gen_renderbuffers(1),
    ok = gl:bind_renderbuffer(renderbuffer, Renderbuffer),
    ok = gl:renderbuffer_storage(renderbuffer, InternalFormat, 1, 1),
    ok = gl:bind_framebuffer(framebuffer, Framebuffer),
    ok = gl:framebuffer_renderbuffer(framebuffer, color_attachment0, renderbuffer, Renderbuffer),
    ok = gl:draw_buffers([color_attachment0]),
    {ok, framebuffer_complete} = gl:check_framebuffer_status(framebuffer),
    ok = gl:clear_buffer(Type, color, 0, Value),
    ok = gl:delete_framebuffers([Framebuffer]),
    ok = gl:delete_renderbuffers([Renderbuffer]).

clear_buffer_depth_stencil_check() ->
    {ok, [Framebuffer]} = gl:gen_framebuffers(1),
    {ok, [ColorRenderbuffer]} = gl:gen_renderbuffers(1),
    {ok, [DepthStencilRenderbuffer]} = gl:gen_renderbuffers(1),
    ok = gl:bind_framebuffer(framebuffer, Framebuffer),
    ok = gl:bind_renderbuffer(renderbuffer, ColorRenderbuffer),
    ok = gl:renderbuffer_storage(renderbuffer, rgba4, 1, 1),
    ok = gl:framebuffer_renderbuffer(framebuffer, color_attachment0, renderbuffer, ColorRenderbuffer),
    ok = gl:bind_renderbuffer(renderbuffer, DepthStencilRenderbuffer),
    ok = gl:renderbuffer_storage(renderbuffer, depth24_stencil8, 1, 1),
    ok = gl:framebuffer_renderbuffer(framebuffer, depth_stencil_attachment, renderbuffer, DepthStencilRenderbuffer),
    ok = gl:draw_buffers([color_attachment0]),
    {ok, framebuffer_complete} = gl:check_framebuffer_status(framebuffer),
    ok = gl:clear_buffer_depth_stencil(0, 1.0, 0),
    ok = gl:delete_framebuffers([Framebuffer]),
    ok = gl:delete_renderbuffers([ColorRenderbuffer, DepthStencilRenderbuffer]).

copy_tex_image_check() ->
    {ok, [Framebuffer]} = gl:gen_framebuffers(1),
    {ok, [Renderbuffer]} = gl:gen_renderbuffers(1),
    ok = gl:bind_renderbuffer(renderbuffer, Renderbuffer),
    ok = gl:renderbuffer_storage(renderbuffer, rgba4, 1, 1),
    ok = gl:bind_framebuffer(framebuffer, Framebuffer),
    ok = gl:framebuffer_renderbuffer(framebuffer, color_attachment0, renderbuffer, Renderbuffer),
    {ok, framebuffer_complete} = gl:check_framebuffer_status(framebuffer),
    {ok, [Texture2D]} = gl:gen_textures(1),
    ok = gl:bind_texture(texture_2d, Texture2D),
    ok = gl:copy_tex_image_2d(texture_2d, 0, rgba, 0, 0, 1, 1, 0),
    ok = gl:copy_tex_sub_image_2d(texture_2d, 0, 0, 0, 0, 0, 1, 1),
    {ok, [Texture3D]} = gl:gen_textures(1),
    ok = gl:bind_texture(texture_3d, Texture3D),
    ok = gl:tex_storage_3d(texture_3d, 1, rgba8, 1, 1, 1),
    ok = gl:copy_tex_sub_image_3d(texture_3d, 0, 0, 0, 0, 0, 0, 1, 1),
    ok = gl:bind_texture(texture_2d, none),
    ok = gl:bind_texture(texture_3d, none),
    ok = gl:delete_textures([Texture2D, Texture3D]),
    ok = gl:delete_framebuffers([Framebuffer]),
    ok = gl:delete_renderbuffers([Renderbuffer]).

transform_feedback_varyings_check(VertexSource, FragmentSource) ->
    {ok, VertexShader} = gl:create_shader(vertex_shader),
    ok = gl:shader_source(VertexShader, [VertexSource]),
    {ok, VertexShaderSource} = gl:get_shader_source(VertexShader, 4096),
    assert_nonempty_binary(VertexShaderSource),
    ok = gl:compile_shader(VertexShader),
    {ok, true} = gl:get_shader_compile_status(VertexShader),
    {ok, VertexShaderInfoLog} = gl:get_shader_info_log(VertexShader, 1024),
    assert_binary(VertexShaderInfoLog),
    {ok, FragmentShader} = gl:create_shader(fragment_shader),
    ok = gl:shader_source(FragmentShader, [FragmentSource]),
    {ok, FragmentShaderSource} = gl:get_shader_source(FragmentShader, 4096),
    assert_nonempty_binary(FragmentShaderSource),
    ok = gl:compile_shader(FragmentShader),
    {ok, true} = gl:get_shader_compile_status(FragmentShader),
    {ok, FragmentShaderInfoLog} = gl:get_shader_info_log(FragmentShader, 1024),
    assert_binary(FragmentShaderInfoLog),
    {ok, Program} = gl:create_program(),
    ok = gl:attach_shader(Program, VertexShader),
    ok = gl:attach_shader(Program, FragmentShader),
    ok = gl:transform_feedback_varyings(Program, [<<"tf_value">>], interleaved_attribs),
    ok = gl:link_program(Program),
    {ok, ProgramInfoLog} = gl:get_program_info_log(Program, 1024),
    assert_binary(ProgramInfoLog),
    {ok, true} = gl:get_program_link_status(Program),
    ok = gl:detach_shader(Program, VertexShader),
    ok = gl:detach_shader(Program, FragmentShader),
    ok = gl:delete_shader(VertexShader),
    ok = gl:delete_shader(FragmentShader),
    ok = gl:delete_program(Program).

es_transform_feedback_vertex_source() ->
    <<"#version 300 es\nout float tf_value;\nvoid main() { tf_value = 1.0; gl_Position = vec4(0.0); }\n">>.

es_transform_feedback_fragment_source() ->
    <<"#version 300 es\nprecision mediump float;\nout vec4 frag_color;\nvoid main() { frag_color = vec4(1.0); }\n">>.

uniform_block_check(VertexSource, FragmentSource) ->
    {ok, VertexShader} = gl:create_shader(vertex_shader),
    ok = gl:shader_source(VertexShader, [VertexSource]),
    {ok, VertexShaderSource} = gl:get_shader_source(VertexShader, 4096),
    assert_nonempty_binary(VertexShaderSource),
    ok = gl:compile_shader(VertexShader),
    {ok, true} = gl:get_shader_compile_status(VertexShader),
    {ok, VertexShaderInfoLog} = gl:get_shader_info_log(VertexShader, 1024),
    assert_binary(VertexShaderInfoLog),
    {ok, FragmentShader} = gl:create_shader(fragment_shader),
    ok = gl:shader_source(FragmentShader, [FragmentSource]),
    {ok, FragmentShaderSource} = gl:get_shader_source(FragmentShader, 4096),
    assert_nonempty_binary(FragmentShaderSource),
    ok = gl:compile_shader(FragmentShader),
    {ok, true} = gl:get_shader_compile_status(FragmentShader),
    {ok, FragmentShaderInfoLog} = gl:get_shader_info_log(FragmentShader, 1024),
    assert_binary(FragmentShaderInfoLog),
    {ok, BlockProgram} = gl:create_program(),
    ok = gl:attach_shader(BlockProgram, VertexShader),
    ok = gl:attach_shader(BlockProgram, FragmentShader),
    ok = gl:link_program(BlockProgram),
    {ok, true} = gl:get_program_link_status(BlockProgram),
    {ok, BlockIndex} = gl:get_uniform_block_index(BlockProgram, <<"CanaryBlock">>),
    ?assert(is_integer(BlockIndex)),
    ?assert(BlockIndex =/= 16#FFFFFFFF),
    ok = gl:uniform_block_binding(BlockProgram, BlockIndex, 0),
    ok = gl:detach_shader(BlockProgram, VertexShader),
    ok = gl:detach_shader(BlockProgram, FragmentShader),
    ok = gl:delete_shader(VertexShader),
    ok = gl:delete_shader(FragmentShader),
    ok = gl:delete_program(BlockProgram).

es_uniform_block_vertex_source() ->
    <<"#version 300 es\nlayout(std140) uniform CanaryBlock { vec4 canary_position; };\nvoid main() { gl_Position = canary_position; }\n">>.

es_uniform_block_fragment_source() ->
    <<"#version 300 es\nprecision mediump float;\nout vec4 frag_color;\nvoid main() { frag_color = vec4(1.0); }\n">>.

fragment_data_location_query_check() ->
    {ok, VertexShader} = gl:create_shader(vertex_shader),
    ok = gl:shader_source(VertexShader, [es_fragment_data_vertex_source()]),
    {ok, VertexShaderSource} = gl:get_shader_source(VertexShader, 4096),
    assert_nonempty_binary(VertexShaderSource),
    ok = gl:compile_shader(VertexShader),
    {ok, true} = gl:get_shader_compile_status(VertexShader),
    {ok, VertexShaderInfoLog} = gl:get_shader_info_log(VertexShader, 1024),
    assert_binary(VertexShaderInfoLog),
    {ok, FragmentShader} = gl:create_shader(fragment_shader),
    ok = gl:shader_source(FragmentShader, [es_fragment_data_fragment_source()]),
    {ok, FragmentShaderSource} = gl:get_shader_source(FragmentShader, 4096),
    assert_nonempty_binary(FragmentShaderSource),
    ok = gl:compile_shader(FragmentShader),
    {ok, true} = gl:get_shader_compile_status(FragmentShader),
    {ok, FragmentShaderInfoLog} = gl:get_shader_info_log(FragmentShader, 1024),
    assert_binary(FragmentShaderInfoLog),
    {ok, Program} = gl:create_program(),
    ok = gl:attach_shader(Program, VertexShader),
    ok = gl:attach_shader(Program, FragmentShader),
    ok = gl:link_program(Program),
    {ok, ProgramInfoLog} = gl:get_program_info_log(Program, 1024),
    assert_binary(ProgramInfoLog),
    {ok, true} = gl:get_program_link_status(Program),
    {ok, Location} = gl:get_frag_data_location(Program, <<"frag_color">>),
    ?assert(is_integer(Location)),
    ?assert(Location >= 0),
    ok = gl:detach_shader(Program, VertexShader),
    ok = gl:detach_shader(Program, FragmentShader),
    ok = gl:delete_shader(VertexShader),
    ok = gl:delete_shader(FragmentShader),
    ok = gl:delete_program(Program).

es_fragment_data_vertex_source() ->
    <<"#version 300 es\nvoid main() { gl_Position = vec4(0.0); }\n">>.

es_fragment_data_fragment_source() ->
    <<"#version 300 es\nprecision mediump float;\nout vec4 frag_color;\nvoid main() { frag_color = vec4(1.0); }\n">>.

program_pipeline_control_check(Program) ->
    {ok, [Pipeline]} = gl:gen_program_pipelines(1),
    ok = gl:bind_program_pipeline(Pipeline),
    ok = gl:use_program_stages(Pipeline, [vertex_shader_bit, fragment_shader_bit], Program),
    ok = gl:active_shader_program(Pipeline, Program),
    ok = gl:validate_program_pipeline(Pipeline),
    {ok, PipelineInfoLog} = gl:get_program_pipeline_info_log(Pipeline, 1024),
    assert_binary(PipelineInfoLog),
    {ok, PipelineInfoLogLength} = gl:get_program_pipeline_info_log_length(Pipeline),
    assert_non_negative_integer(PipelineInfoLogLength),
    {ok, PipelineValidationStatus} = gl:get_program_pipeline_validation_status(Pipeline),
    ?assert(is_boolean(PipelineValidationStatus)),
    ok = gl:delete_program_pipelines([Pipeline]).

sampler_binding_check(Sampler) ->
    ok = gl:sampler_parameter(f, Sampler, texture_min_lod, 0.0),
    ok = gl:sampler_parameter(f, Sampler, texture_max_lod, [1000.0]),
    ok = gl:sampler_parameter(i, Sampler, texture_min_filter, 16#2601),
    ok = gl:sampler_parameter(i, Sampler, texture_wrap_s, [16#812F]),
    ok = gl:bind_sampler(0, Sampler),
    ok = gl:bind_sampler(0, none).

compute_dispatch_check(Source) ->
    {ok, ComputeShader} = gl:create_shader(compute_shader),
    ok = gl:shader_source(ComputeShader, [Source]),
    ok = gl:compile_shader(ComputeShader),
    {ok, true} = gl:get_shader_compile_status(ComputeShader),
    {ok, ComputeProgram} = gl:create_program(),
    ok = gl:attach_shader(ComputeProgram, ComputeShader),
    ok = gl:link_program(ComputeProgram),
    {ok, true} = gl:get_program_link_status(ComputeProgram),
    ok = gl:use_program(ComputeProgram),
    ok = gl:dispatch_compute(1, 1, 1),
    {ok, [IndirectBuffer]} = gl:gen_buffers(1),
    ok = gl:bind_buffer(dispatch_indirect_buffer, IndirectBuffer),
    ok = gl:buffer_data(dispatch_indirect_buffer, <<1:32/native-unsigned, 1:32/native-unsigned, 1:32/native-unsigned>>, static_draw),
    ok = gl:dispatch_compute_indirect(0),
    ok = gl:bind_buffer(dispatch_indirect_buffer, none),
    ok = gl:delete_buffers([IndirectBuffer]),
    ok = gl:use_program(none),
    ok = gl:detach_shader(ComputeProgram, ComputeShader),
    ok = gl:delete_shader(ComputeShader),
    {ok, false} = gl:is_shader(ComputeShader),
    ok = gl:delete_program(ComputeProgram),
    {ok, false} = gl:is_program(ComputeProgram).

assert_nonempty_binary(Value) ->
    ?assert(is_binary(Value)),
    ?assert(byte_size(Value) > 0).

assert_binary(Value) ->
    ?assert(is_binary(Value)).

state_limit_queries_check() ->
    {ok, MaxTextureSize} = gl:get_max_texture_size(),
    assert_non_negative_integer(MaxTextureSize),
    {ok, SubpixelBits} = gl:get_subpixel_bits(),
    assert_non_negative_integer(SubpixelBits),
    {ok, SampleBuffersCount} = gl:get_sample_buffers_count(),
    assert_non_negative_integer(SampleBuffersCount),
    {ok, SamplesCount} = gl:get_samples_count(),
    assert_non_negative_integer(SamplesCount),
    {ok, NumCompressedTextureFormats} = gl:get_num_compressed_texture_formats(),
    assert_non_negative_integer(NumCompressedTextureFormats),
    {ok, MaxVertexAttribs} = gl:get_max_vertex_attribs(),
    assert_non_negative_integer(MaxVertexAttribs),
    {ok, MaxTextureImageUnits} = gl:get_max_texture_image_units(),
    assert_non_negative_integer(MaxTextureImageUnits),
    {ok, MaxVertexTextureImageUnits} = gl:get_max_vertex_texture_image_units(),
    assert_non_negative_integer(MaxVertexTextureImageUnits),
    {ok, MaxCombinedTextureImageUnits} = gl:get_max_combined_texture_image_units(),
    assert_non_negative_integer(MaxCombinedTextureImageUnits),
    {ok, MaxCubeMapTextureSize} = gl:get_max_cube_map_texture_size(),
    assert_non_negative_integer(MaxCubeMapTextureSize),
    {ok, MaxRenderbufferSize} = gl:get_max_renderbuffer_size(),
    assert_non_negative_integer(MaxRenderbufferSize),
    ok.

state_detail_queries_check() ->
    {ok, PackAlignment} = gl:get_pack_alignment(),
    assert_non_negative_integer(PackAlignment),
    {ok, UnpackAlignment} = gl:get_unpack_alignment(),
    assert_non_negative_integer(UnpackAlignment),
    {ok, MaxElementsVertices} = gl:get_max_elements_vertices(),
    assert_non_negative_integer(MaxElementsVertices),
    {ok, MaxElementsIndices} = gl:get_max_elements_indices(),
    assert_non_negative_integer(MaxElementsIndices),
    {ok, NumShaderBinaryFormats} = gl:get_num_shader_binary_formats(),
    assert_non_negative_integer(NumShaderBinaryFormats),
    {ok, MaxVaryingVectors} = gl:get_max_varying_vectors(),
    assert_non_negative_integer(MaxVaryingVectors),
    ok.

indexed_string_check() ->
    {ok, NumExtensions} = gl:get_num_extensions(),
    case NumExtensions of
        Count when Count > 0 ->
            {ok, Extension} = gl:get_string(extensions, 0),
            assert_nonempty_binary(Extension);
        _ ->
            ok
    end.

state_limit_expansion_queries_check() ->
    {ok, MajorVersion} = gl:get_major_version(),
    assert_non_negative_integer(MajorVersion),
    {ok, MinorVersion} = gl:get_minor_version(),
    assert_non_negative_integer(MinorVersion),
    {ok, NumExtensions} = gl:get_num_extensions(),
    assert_non_negative_integer(NumExtensions),
    {ok, Max3DTextureSize} = gl:get_max_3d_texture_size(),
    assert_non_negative_integer(Max3DTextureSize),
    {ok, MaxDrawBuffers} = gl:get_max_draw_buffers(),
    assert_non_negative_integer(MaxDrawBuffers),
    {ok, MaxColorAttachments} = gl:get_max_color_attachments(),
    assert_non_negative_integer(MaxColorAttachments),
    {ok, MaxSamples} = gl:get_max_samples(),
    assert_non_negative_integer(MaxSamples),
    {ok, MaxArrayTextureLayers} = gl:get_max_array_texture_layers(),
    assert_non_negative_integer(MaxArrayTextureLayers),
    {ok, MaxVaryingComponents} = gl:get_max_varying_components(),
    assert_non_negative_integer(MaxVaryingComponents),
    {ok, MaxVertexUniformComponents} = gl:get_max_vertex_uniform_components(),
    assert_non_negative_integer(MaxVertexUniformComponents),
    {ok, MaxFragmentUniformComponents} = gl:get_max_fragment_uniform_components(),
    assert_non_negative_integer(MaxFragmentUniformComponents),
    {ok, MaxVertexUniformBlocks} = gl:get_max_vertex_uniform_blocks(),
    assert_non_negative_integer(MaxVertexUniformBlocks),
    {ok, MaxFragmentUniformBlocks} = gl:get_max_fragment_uniform_blocks(),
    assert_non_negative_integer(MaxFragmentUniformBlocks),
    {ok, MaxCombinedUniformBlocks} = gl:get_max_combined_uniform_blocks(),
    assert_non_negative_integer(MaxCombinedUniformBlocks),
    {ok, MaxUniformBufferBindings} = gl:get_max_uniform_buffer_bindings(),
    assert_non_negative_integer(MaxUniformBufferBindings),
    {ok, MaxUniformBlockSize} = gl:get_max_uniform_block_size(),
    assert_non_negative_integer(MaxUniformBlockSize),
    {ok, UniformBufferOffsetAlignment} = gl:get_uniform_buffer_offset_alignment(),
    assert_non_negative_integer(UniformBufferOffsetAlignment),
    {ok, MaxVertexUniformVectors} = gl:get_max_vertex_uniform_vectors(),
    assert_non_negative_integer(MaxVertexUniformVectors),
    {ok, MaxFragmentUniformVectors} = gl:get_max_fragment_uniform_vectors(),
    assert_non_negative_integer(MaxFragmentUniformVectors),
    ok.

pixel_store_state_queries_check() ->
    {ok, PackRowLength} = gl:get_pack_row_length(),
    assert_non_negative_integer(PackRowLength),
    {ok, PackSkipRows} = gl:get_pack_skip_rows(),
    assert_non_negative_integer(PackSkipRows),
    {ok, PackSkipPixels} = gl:get_pack_skip_pixels(),
    assert_non_negative_integer(PackSkipPixels),
    {ok, UnpackRowLength} = gl:get_unpack_row_length(),
    assert_non_negative_integer(UnpackRowLength),
    {ok, UnpackSkipRows} = gl:get_unpack_skip_rows(),
    assert_non_negative_integer(UnpackSkipRows),
    {ok, UnpackSkipPixels} = gl:get_unpack_skip_pixels(),
    assert_non_negative_integer(UnpackSkipPixels),
    {ok, UnpackImageHeight} = gl:get_unpack_image_height(),
    assert_non_negative_integer(UnpackImageHeight),
    {ok, UnpackSkipImages} = gl:get_unpack_skip_images(),
    assert_non_negative_integer(UnpackSkipImages),
    ok.

resource_limit_queries_check() ->
    {ok, MaxComputeUniformBlocks} = gl:get_max_compute_uniform_blocks(),
    assert_non_negative_integer(MaxComputeUniformBlocks),
    {ok, MaxComputeTextureImageUnits} = gl:get_max_compute_texture_image_units(),
    assert_non_negative_integer(MaxComputeTextureImageUnits),
    {ok, MaxComputeImageUniforms} = gl:get_max_compute_image_uniforms(),
    assert_non_negative_integer(MaxComputeImageUniforms),
    {ok, MaxComputeSharedMemorySize} = gl:get_max_compute_shared_memory_size(),
    assert_non_negative_integer(MaxComputeSharedMemorySize),
    {ok, MaxComputeUniformComponents} = gl:get_max_compute_uniform_components(),
    assert_non_negative_integer(MaxComputeUniformComponents),
    {ok, MaxComputeAtomicCounterBuffers} = gl:get_max_compute_atomic_counter_buffers(),
    assert_non_negative_integer(MaxComputeAtomicCounterBuffers),
    {ok, MaxComputeAtomicCounters} = gl:get_max_compute_atomic_counters(),
    assert_non_negative_integer(MaxComputeAtomicCounters),
    {ok, MaxComputeWorkGroupInvocations} = gl:get_max_compute_work_group_invocations(),
    assert_non_negative_integer(MaxComputeWorkGroupInvocations),
    {ok, MaxImageUnits} = gl:get_max_image_units(),
    assert_non_negative_integer(MaxImageUnits),
    {ok, MaxVertexImageUniforms} = gl:get_max_vertex_image_uniforms(),
    assert_non_negative_integer(MaxVertexImageUniforms),
    {ok, MaxFragmentImageUniforms} = gl:get_max_fragment_image_uniforms(),
    assert_non_negative_integer(MaxFragmentImageUniforms),
    {ok, MaxCombinedImageUniforms} = gl:get_max_combined_image_uniforms(),
    assert_non_negative_integer(MaxCombinedImageUniforms),
    {ok, MaxVertexShaderStorageBlocks} = gl:get_max_vertex_shader_storage_blocks(),
    assert_non_negative_integer(MaxVertexShaderStorageBlocks),
    {ok, MaxFragmentShaderStorageBlocks} = gl:get_max_fragment_shader_storage_blocks(),
    assert_non_negative_integer(MaxFragmentShaderStorageBlocks),
    {ok, MaxComputeShaderStorageBlocks} = gl:get_max_compute_shader_storage_blocks(),
    assert_non_negative_integer(MaxComputeShaderStorageBlocks),
    {ok, MaxCombinedShaderStorageBlocks} = gl:get_max_combined_shader_storage_blocks(),
    assert_non_negative_integer(MaxCombinedShaderStorageBlocks),
    {ok, MaxShaderStorageBufferBindings} = gl:get_max_shader_storage_buffer_bindings(),
    assert_non_negative_integer(MaxShaderStorageBufferBindings),
    {ok, ShaderStorageBufferOffsetAlignment} = gl:get_shader_storage_buffer_offset_alignment(),
    assert_non_negative_integer(ShaderStorageBufferOffsetAlignment),
    {ok, MaxVertexAtomicCounterBuffers} = gl:get_max_vertex_atomic_counter_buffers(),
    assert_non_negative_integer(MaxVertexAtomicCounterBuffers),
    {ok, MaxFragmentAtomicCounterBuffers} = gl:get_max_fragment_atomic_counter_buffers(),
    assert_non_negative_integer(MaxFragmentAtomicCounterBuffers),
    {ok, MaxCombinedAtomicCounterBuffers} = gl:get_max_combined_atomic_counter_buffers(),
    assert_non_negative_integer(MaxCombinedAtomicCounterBuffers),
    {ok, MaxVertexAtomicCounters} = gl:get_max_vertex_atomic_counters(),
    assert_non_negative_integer(MaxVertexAtomicCounters),
    {ok, MaxFragmentAtomicCounters} = gl:get_max_fragment_atomic_counters(),
    assert_non_negative_integer(MaxFragmentAtomicCounters),
    {ok, MaxCombinedAtomicCounters} = gl:get_max_combined_atomic_counters(),
    assert_non_negative_integer(MaxCombinedAtomicCounters),
    {ok, MaxAtomicCounterBufferBindings} = gl:get_max_atomic_counter_buffer_bindings(),
    assert_non_negative_integer(MaxAtomicCounterBufferBindings),
    ok.

fixed_resource_limit_queries_check() ->
    assert_non_negative_query(fun gl:get_max_transform_feedback_separate_components/0),
    assert_non_negative_query(fun gl:get_max_transform_feedback_interleaved_components/0),
    assert_non_negative_query(fun gl:get_max_transform_feedback_separate_attribs/0),
    assert_integer_query(fun gl:get_min_program_texel_offset/0),
    assert_non_negative_query(fun gl:get_max_program_texel_offset/0),
    assert_integer_query(fun gl:get_min_program_texture_gather_offset/0),
    assert_non_negative_query(fun gl:get_max_program_texture_gather_offset/0),
    assert_non_negative_query(fun gl:get_num_program_binary_formats/0),
    assert_non_negative_query(fun gl:get_max_uniform_locations/0),
    assert_non_negative_query(fun gl:get_max_framebuffer_width/0),
    assert_non_negative_query(fun gl:get_max_framebuffer_height/0),
    assert_non_negative_query(fun gl:get_max_framebuffer_samples/0),
    ok.

frontier_scalar_queries_check() ->
    assert_boolean_query(fun gl:get_shader_compiler_supported/0),
    assert_non_negative_query(fun gl:get_max_sample_mask_words/0),
    assert_non_negative_query(fun gl:get_max_color_texture_samples/0),
    assert_non_negative_query(fun gl:get_max_depth_texture_samples/0),
    assert_non_negative_query(fun gl:get_max_integer_samples/0),
    assert_non_negative_query(fun gl:get_max_vertex_attrib_relative_offset/0),
    assert_non_negative_query(fun gl:get_max_vertex_attrib_bindings/0),
    assert_non_negative_query(fun gl:get_max_vertex_attrib_stride/0),
    assert_non_negative_query(fun gl:get_max_vertex_output_components/0),
    assert_non_negative_query(fun gl:get_max_fragment_input_components/0),
    assert_non_negative_query(fun gl:get_max_combined_shader_output_resources/0),
    ok.

int64_limit_queries_check() ->
    assert_non_negative_query(fun gl:get_max_combined_vertex_uniform_components/0),
    assert_non_negative_query(fun gl:get_max_combined_fragment_uniform_components/0),
    assert_non_negative_query(fun gl:get_max_combined_compute_uniform_components/0),
    assert_non_negative_query(fun gl:get_max_shader_storage_block_size/0),
    assert_non_negative_query(fun gl:get_max_atomic_counter_buffer_size/0),
    ok.

assert_shader_metadata(Shader) ->
    {ok, false} = gl:get_shader_delete_status(Shader),
    {ok, SourceLength} = gl:get_shader_source_length(Shader),
    assert_positive_integer(SourceLength),
    {ok, InfoLogLength} = gl:get_shader_info_log_length(Shader),
    assert_non_negative_integer(InfoLogLength).

assert_program_metadata(Program, AttachedShadersCount) ->
    {ok, false} = gl:get_program_delete_status(Program),
    {ok, InfoLogLength} = gl:get_program_info_log_length(Program),
    assert_non_negative_integer(InfoLogLength),
    {ok, AttachedShadersCount} = gl:get_program_attached_shaders_count(Program),
    {ok, ActiveAttributesCount} = gl:get_program_active_attributes_count(Program),
    assert_non_negative_integer(ActiveAttributesCount),
    {ok, ActiveAttributeMaxLength} = gl:get_program_active_attribute_max_length(Program),
    assert_non_negative_integer(ActiveAttributeMaxLength),
    {ok, ActiveUniformsCount} = gl:get_program_active_uniforms_count(Program),
    assert_non_negative_integer(ActiveUniformsCount),
    {ok, ActiveUniformMaxLength} = gl:get_program_active_uniform_max_length(Program),
    assert_non_negative_integer(ActiveUniformMaxLength),
    {ok, ActiveUniformBlocksCount} = gl:get_program_active_uniform_blocks_count(Program),
    assert_non_negative_integer(ActiveUniformBlocksCount),
    {ok, ActiveUniformBlockMaxNameLength} = gl:get_program_active_uniform_block_max_name_length(Program),
    assert_non_negative_integer(ActiveUniformBlockMaxNameLength),
    {ok, TransformFeedbackVaryingsCount} = gl:get_program_transform_feedback_varyings_count(Program),
    assert_non_negative_integer(TransformFeedbackVaryingsCount),
    {ok, TransformFeedbackVaryingMaxLength} = gl:get_program_transform_feedback_varying_max_length(Program),
    assert_non_negative_integer(TransformFeedbackVaryingMaxLength),
    {ok, ProgramBinaryLength} = gl:get_program_binary_length(Program),
    assert_non_negative_integer(ProgramBinaryLength),
    {ok, ActiveAtomicCounterBuffersCount} = gl:get_program_active_atomic_counter_buffers_count(Program),
    assert_non_negative_integer(ActiveAtomicCounterBuffersCount),
    {ok, ProgramSeparable} = gl:get_program_separable(Program),
    ?assert(is_boolean(ProgramSeparable)).

assert_active_reflection_metadata(Program) ->
    {ok, ActiveAttributesCount} = gl:get_program_active_attributes_count(Program),
    ?assert(ActiveAttributesCount >= 1),
    {ok, ActiveAttributeMaxLength} = gl:get_program_active_attribute_max_length(Program),
    assert_positive_integer(ActiveAttributeMaxLength),
    ActiveAttributes = [
        begin
            {ok, Size, Type, Name} = gl:get_active_attrib(Program, Index, ActiveAttributeMaxLength),
            {Size, Type, Name}
        end
     || Index <- lists:seq(0, ActiveAttributesCount - 1)
    ],
    ?assert(lists:member({1, float_vec4, <<"position">>}, ActiveAttributes)),

    {ok, ActiveUniformsCount} = gl:get_program_active_uniforms_count(Program),
    ?assert(ActiveUniformsCount >= 1),
    {ok, ActiveUniformMaxLength} = gl:get_program_active_uniform_max_length(Program),
    assert_positive_integer(ActiveUniformMaxLength),
    ActiveUniforms = [
        begin
            {ok, Size, Type, Name} = gl:get_active_uniform(Program, Index, ActiveUniformMaxLength),
            {Size, Type, Name}
        end
     || Index <- lists:seq(0, ActiveUniformsCount - 1)
    ],
    ?assert(lists:member({1, float_vec4, <<"u_color">>}, ActiveUniforms)).

read_pixels_check() ->
    {ok, [Renderbuffer]} = gl:gen_renderbuffers(1),
    ok = gl:bind_renderbuffer(renderbuffer, Renderbuffer),
    ok = gl:renderbuffer_storage(renderbuffer, rgba4, 1, 1),
    {ok, [Framebuffer]} = gl:gen_framebuffers(1),
    ok = gl:bind_framebuffer(framebuffer, Framebuffer),
    ok = gl:framebuffer_renderbuffer(framebuffer, color_attachment0, renderbuffer, Renderbuffer),
    {ok, framebuffer_complete} = gl:check_framebuffer_status(framebuffer),
    ok = gl:clear_color(0.0, 0.0, 0.0, 1.0),
    ok = gl:clear([color_buffer_bit]),
    {ok, <<0, 0, 0, 255>>} = gl:read_pixels(0, 0, 1, 1, rgba, unsigned_byte, 4),
    ok = gl:delete_framebuffers([Framebuffer]),
    ok = gl:delete_renderbuffers([Renderbuffer]),
    ok.

assert_positive_integer(Value) ->
    ?assert(is_integer(Value)),
    ?assert(Value > 0).

assert_non_negative_query(Fun) ->
    {ok, Value} = Fun(),
    assert_non_negative_integer(Value).

assert_integer_query(Fun) ->
    {ok, Value} = Fun(),
    ?assert(is_integer(Value)).

assert_boolean_query(Fun) ->
    {ok, Value} = Fun(),
    ?assert(is_boolean(Value)).

assert_non_negative_integer(Value) ->
    ?assert(is_integer(Value)),
    ?assert(Value >= 0).
